name: backend-challenge
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21-ea
      - name: Build project and run tests
        run: mvn clean verify
      - name: Login Docker
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build Docker
        run: docker build -t giovanacarvalhodev/challenge-backend .
      - name: Push Image Docker
        run: docker push giovanacarvalhodev/challenge-backend

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull for DockerHub
        run: docker pull giovanacarvalhodev/challenge-backend:latest
      - name: Stop Docker Container if running
        run: docker stop challenge || true
      - name: Remove Docker Container if exists
        run: docker rm challenge || true
      - name: Run docker container
        run: docker run -d -p 8080:8080 --name challenge giovanacarvalhodev/challenge-backend